### ISSUE TITLE
[CGR-1] Code Style and Linting

### ISSUE THREAD

**Issue by kalisjoshua** [QuickenLoans/js-concord#2]
Projects should conform to a consistent coding style and those rules should be enforced by a linter. During "early" adoption of CGRs, style deviations shouldn't "break" a build but once compliance is reached that should change.

**Comment by kalisjoshua** [comment]
I think that starting with [AirBnB] and refining a little is a good idea. Does any feel that there is a better place to start?


[AirBnB]: https://github.com/airbnb/javascript

**Comment by kalisjoshua** [comment]
Would the (primary) suggested linting tool be [ESLint]?


[ESLint]: http://eslint.org/

**Comment by RichardMartinez** [comment]
I have used JSHint and ESLint and my preference is ESLint. I find it easier to use. I think it has better documentation and is more up to date. Additionally, we would be able to use [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb), if we decided to start with the [AirBnB JavaScript Style Guide](https://github.com/airbnb/javascript).

**Comment by kalisjoshua** [comment]
closed by #10
