### ISSUE TITLE
[CGR-2] Preprocessor

### ISSUE THREAD

**Issue by kalisjoshua** [QuickenLoans/js-concord#3]
A common preprocessor should be used across projects so that language features are consistent between different projects.

**Comment by kalisjoshua** [comment]
The only viable options I see right now are:

  - [Babel](https://babeljs.io/) (primary)
  - [TypeScript](https://www.typescriptlang.org/) (alternative)

Does anyone believe differently? My justification is that I think that we should recommend writing as close to compiled output as possible - if you intent to write JS, just write JS - this would reject "compile-to-js" languages: CoffeeScript, PureScript, Elm, etc.

**Comment by scottux** [comment]
I think TypeScript is the better option here. 

https://vsavkin.com/writing-angular-2-in-typescript-1fa77c78d8e8
https://medium.com/@basarat/typescript-won-a4e0dfde4b08

>TypeScript takes 95% of the usefulness of a good statically-typed language and brings it to the JavaScript ecosystem. You still feel like you write ES6: you keep using the same standard library, same third-party libraries, same idioms, and many of the same tools (e.g., Chrome dev tools). It gives you a lot without forcing you out of the JavaScript ecosystem.

**Comment by kalisjoshua** [comment]
Interesting. @scottux why do you prefer TypeScript? Type checking, or other language features?

**Comment by shaunwest** [comment]
TS seems to be gaining traction lately. It's way outpacing Babel on NPM for instance.

https://medium.freecodecamp.com/its-time-to-give-typescript-another-chance-2caaf7fabe61#.q9y184p50

> TypeScript is like a highly-advanced linter, able to check documentation and warn when code is not being used as intended.
It provides immediate feedback and a better development experience for all future users of your code.

**Comment by kalisjoshua** [comment]
I like that Babel is sticking closer to standard specifications; TypeScript defining its own standard is less appealing. TypeScript is still interesting however.

@scottux looking forward to hear about what you learn.

**Comment by RichardMartinez** [comment]
@scottux When I was working with TypeScript a while ago I was using that flow: 
> typescript -> babel -> current javascript

That way I could use all the latest ES features. It may not be as useful anymore.

**Comment by kalisjoshua** [comment]
I've created a Pull Request #13 for this issue.

**Comment by kalisjoshua** [comment]
Closed by #13.
